schedule:
- end_s: 999999.0
  start_s: 0.0
  view: view_main
views:
  view_main:
    bed_polygon:
    - - 403
      - 397
    - - 607
      - 293
    - - 911
      - 374
    - - 781
      - 526
    - - 413
      - 402
    description: Mattress polygon for view_main
