schedule:
- end_s: 30.0
  start_s: 0.0
  view: view_main
views:
  view_main:
    bed_polygon:
    - - 140
      - 418
    - - 632
      - 263
    - - 889
      - 426
    - - 186
      - 695
    - - 135
      - 433
    description: Mattress polygon for test_4 static room view
